function allergenDB = createAllergenDatabase()
% createAllergenDatabase - Türkiye Gıda Kodeksi'ne uygun alerjen veritabanı oluşturur
%
% KULLANIM:
%   allergenDB = createAllergenDatabase()
%
% ÇIKTI:
%   allergenDB - Her alerjen kategorisi için terim listesi içeren struct
%
% AÇIKLAMA:
%   Bu fonksiyon, gıda etiketlerinde yaygın olarak kullanılan alerjen
%   terimlerini kategorize ederek bir veritabanı oluşturur. OCR ile
%   okunan metinlerde alerjen tespiti için kullanılır.
%
% YAZAR: Veri Mühendisliği Ekibi
% TARİH: 27 Aralık 2025

    % Struct yapısını başlat
    allergenDB = struct();
    
    %% 1. SÜT VE SÜT ÜRÜNLERİ
    % Laktoz intoleransı ve süt alerjisi yaygın olup, süt proteini içeren
    % tüm ürünler ciddi alerjik reaksiyonlara neden olabilir.
    allergenDB.Sut = {
        'süt', 'süt tozu', 'tam yağlı süt tozu', 'yağsız süt tozu', ...
        'laktoz', 'laktozlu', 'laktik asit', ...
        'kazein', 'kazeinat', 'sodyum kazeinat', 'kalsiyum kazeinat', ...
        'peynir altı suyu', 'peynir altı suyu tozu', ...
        'krema', 'tereyağı', 'süt yağı', 'yoğurt', 'yoğurt kültürü', ...
        'peynir', 'beyaz peynir', 'kaşar', 'krem peynir', ...
        'ayran', 'kefir', 'süt proteini', ...
        'laktoglobulin', 'laktalbumin', ...
        'eser miktarda süt', 'süt içerebilir', 'süt ürünleri içerebilir', ...
        'süt ürünü', 'süt kaynaklı', 'süt bazlı', ...
        'laktoferrin', 'kolostrum'
    };
    
    %% 2. GLUTEN VE TAHILLAR
    % Çölyak hastalığı ve gluten intoleransı olan bireyler için kritik.
    % Buğday, arpa, çavdar ve tritikale içeren tüm ürünler takip edilmeli.
    allergenDB.Gluten = {
        'gluten', 'glutenli', ...
        'buğday', 'buğday unu', 'tam buğday unu', 'beyaz un', ...
        'arpa', 'arpa unu', 'arpa malt', 'malt', 'malt ekstresi', 'maltoz', ...
        'çavdar', 'çavdar unu', ...
        'tritikale', ...
        'bulgur', 'irmik', 'kuskus', 'frik', ...
        'kepek', 'buğday kepeği', 'buğday rüşeymi', ...
        'gluten proteini', 'seitan', ...
        'modifiye nişasta', 'buğday nişastası', ...
        'hidrolize buğday proteini', ...
        'eser miktarda gluten', 'gluten içerebilir', ...
        'buğday içerebilir', 'tahıl içerebilir', ...
        'triticum', 'durum buğdayı', 'spelt', 'kamut', ...
        'kaplıca buğdayı', 'einkorn', 'emmer'
    };
    
    %% 3. KURUYEMİŞLER
    % Anafilaksi gibi hayati tehlike oluşturabilecek en ciddi alerjenlerden.
    % Her kuruyemiş türü ayrı ayrı belirtilmeli.
    
    % 3A. Fıstık (Yer Fıstığı)
    allergenDB.Fistik = {
        'fıstık', 'yer fıstığı', 'yerfıstığı', 'fıstık ezmesi', ...
        'fıstık yağı', 'fıstık tozu', 'fıstık parçaları', ...
        'eser miktarda fıstık', 'fıstık içerebilir', ...
        'fıstık proteini', 'arachis', 'yer fıstığı yağı'
    };
    
    % 3B. Fındık
    allergenDB.Findik = {
        'fındık', 'fındık ezmesi', 'fındık yağı', 'fındık tozu', ...
        'kavrulmuş fındık', 'fındık parçaları', 'fındık aroması', ...
        'eser miktarda fındık', 'fındık içerebilir', ...
        'türk fındığı', 'giresun fındığı', 'hazelnut'
    };
    
    % 3C. Badem
    allergenDB.Badem = {
        'badem', 'badem tozu', 'badem ezmesi', 'badem yağı', ...
        'badem sütü', 'badem unu', 'marcipan', 'marzipan', ...
        'eser miktarda badem', 'badem içerebilir', ...
        'acı badem', 'tatlı badem', 'badem proteini'
    };
    
    % 3D. Ceviz
    allergenDB.Ceviz = {
        'ceviz', 'ceviz içi', 'ceviz tozu', 'ceviz yağı', ...
        'ceviz ezmesi', 'ceviz parçaları', ...
        'eser miktarda ceviz', 'ceviz içerebilir', ...
        'kara ceviz', 'walnut', 'cevizli'
    };
    
    % 3E. Antep Fıstığı
    allergenDB.AntepFistigi = {
        'antep fıstığı', 'antepfıstığı', 'şam fıstığı', ...
        'pistachio', 'antep fıstığı ezmesi', ...
        'antep fıstığı tozu', 'antep fıstığı yağı', ...
        'eser miktarda antep fıstığı', 'antep fıstığı içerebilir', ...
        'antep fıstıklı'
    };
    
    % 3F. Kaju
    allergenDB.Kaju = {
        'kaju', 'kaju fıstığı', 'kaju yağı', 'cashew', ...
        'kaju ezmesi', 'kaju parçaları', ...
        'eser miktarda kaju', 'kaju içerebilir', ...
        'kajulu'
    };
    
    % 3G. Diğer Sert Kabuklu Meyveler
    allergenDB.DigerKuruyemis = {
        'pekan', 'pekan cevizi', 'pecan', ...
        'makademya', 'makadamya', 'macadamia', ...
        'pikan', 'brezilya cevizi', 'brazil nut', ...
        'çam fıstığı', 'çam içi', 'pine nut', ...
        'hindistan cevizi', 'kokos', 'coconut', ...
        'sert kabuklu meyve', 'kuruyemiş', 'kuruyemiş karışımı', ...
        'eser miktarda kuruyemiş', 'kuruyemiş içerebilir', ...
        'sert kabuklu meyve içerebilir', ...
        'leblebi', 'ay çekirdeği', 'kabak çekirdeği', ...
        'yer fındığı', 'susam', 'çekirdek'
    };
    
    %% 4. YUMURTA
    % Özellikle çocuklarda yaygın olan alerjen. Yumurta proteini içeren
    % tüm gıdalar ve katkı maddeleri önemli.
    allergenDB.Yumurta = {
        'yumurta', 'yumurta sarısı', 'yumurta akı', ...
        'yumurta tozu', 'albümin', 'albumin', ...
        'yumurta beyazı', 'yumurta proteini', ...
        'lecitin', 'lesitin', 'yumurta lesitini', ...
        'globulin', 'livettin', 'ovomukoid', ...
        'mayonez', 'mayonezli', ...
        'eser miktarda yumurta', 'yumurta içerebilir', ...
        'tavuk yumurtası', 'yumurta kabuğu tozu', ...
        'kuru yumurta', 'sıvı yumurta', 'pastörize yumurta'
    };
    
    %% 5. SOYA
    % Yaygın kullanılan bitki proteini. Soya alerjisi olanlar için
    % gizli soya içeriğine dikkat edilmeli.
    allergenDB.Soya = {
        'soya', 'soya fasulyesi', 'soya proteini', ...
        'soya unu', 'soya yağı', 'soya sütü', ...
        'soya lesitini', 'soya lecitini', ...
        'tofu', 'tempeh', 'miso', 'edamame', ...
        'soya sosu', 'soya sos', ...
        'hidrolize soya proteini', 'izole soya proteini', ...
        'tekstüre soya proteini', ...
        'eser miktarda soya', 'soya içerebilir', ...
        'soya bazlı', 'soya kaynaklı', ...
        'soya filizi', 'doğal lesitin'
    };
    
    %% 6. DENİZ ÜRÜNLERİ
    % Balık ve kabuklu deniz ürünleri ciddi alerjik reaksiyonlara neden olabilir.
    
    % 6A. Balık
    allergenDB.Balik = {
        'balık', 'balık eti', 'balık proteini', ...
        'hamsi', 'sardalya', 'ton balığı', 'tuna', 'somon', ...
        'levrek', 'çipura', 'palamut', 'istavrit', 'uskumru', ...
        'balık yağı', 'omega-3', 'balık ekstresi', ...
        'anchovy', 'balık sosu', ...
        'eser miktarda balık', 'balık içerebilir', ...
        'morina', 'alabalık', 'mezgit'
    };
    
    % 6B. Kabuklu Deniz Ürünleri
    allergenDB.KabukluDenizUrunleri = {
        'karides', 'karidesli', 'krevat', ...
        'yengeç', 'istakoz', 'ıstakoz', ...
        'kerevit', 'midye', 'istiridye', ...
        'ahtapot', 'kalamar', 'mürekkepbalığı', ...
        'kabuklu deniz ürünü', 'deniz ürünü', 'deniz ürünleri', ...
        'eser miktarda deniz ürünü', 'deniz ürünü içerebilir', ...
        'seafood', 'krustase', 'yumuşakça', ...
        'deniz mahsulleri', 'shellfish'
    };
    
    %% 7. SUSAM
    % Son yıllarda gıda etiketlerinde zorunlu belirtilmesi gereken alerjen.
    % Tahini ve helva gibi ürünlerde yaygın.
    allergenDB.Susam = {
        'susam', 'susam tohumu', 'susamlı', ...
        'tahini', 'tahin', 'tahin helvası', ...
        'susam yağı', 'susam ezmesi', ...
        'kavrulmuş susam', 'siyah susam', 'beyaz susam', ...
        'eser miktarda susam', 'susam içerebilir', ...
        'gomasio', 'sesame', 'susam proteini'
    };
    
    %% 8. HARDAL
    % Özellikle soslar ve baharatlarda kullanılan önemli alerjen.
    allergenDB.Hardal = {
        'hardal', 'hardal tohumu', ...
        'hardal sosu', 'mustafa', 'dijon hardal', ...
        'sarı hardal', 'kahverengi hardal', 'siyah hardal', ...
        'hardal yağı', 'hardal tozu', ...
        'eser miktarda hardal', 'hardal içerebilir', ...
        'mustard', 'hardal proteini'
    };
    
    %% 9. BAKLAGİLLER
    % Mercimek, nohut gibi yaygın baklagiller de alerjen olabilir.
    allergenDB.Baklagiller = {
        'baklagil', 'bakliyat', ...
        'nohut', 'nohut unu', 'humus', 'hummus', ...
        'mercimek', 'yeşil mercimek', 'kırmızı mercimek', ...
        'bezelye', 'bezelye proteini', ...
        'fasulye', 'kuru fasulye', 'barbunya', 'börülce', ...
        'bakla', 'yeşil bakla', ...
        'lupine', 'lupin', 'acı bakla', ...
        'eser miktarda baklagil', 'baklagil içerebilir', ...
        'baklagil unu', 'baklagil proteini', ...
        'mürdümük', 'burçak', 'yonca'
    };
    
    %% 10. KÜKÜRT DİOKSİT VE SÜLFİTLER
    % Kuru meyve, şarap ve işlenmiş gıdalarda koruyucu olarak kullanılır.
    % Astım hastaları için önemli.
    allergenDB.Sulfit = {
        'sülfür dioksit', 'kükürt dioksit', 'kükürtdioksit', ...
        'sülfit', 'sülfitler', 'sulfit', 'sulfitler', ...
        'e220', 'e221', 'e222', 'e223', 'e224', 'e225', 'e226', 'e227', 'e228', ...
        'sodyum sülfit', 'sodyum bisülfit', ...
        'potasyum sülfit', 'potasyum bisülfit', ...
        'kalsiyum sülfit', ...
        'sodyum metabisülfit', 'potasyum metabisülfit', ...
        'eser miktarda sülfit', 'sülfit içerebilir', ...
        'koruyucu madde', 'so2'
    };
    
    %% 11. KEREVZ (SELERİ)
    % AB'de zorunlu alerjen, Türkiye'de de önemli.
    allergenDB.Kereviz = {
        'kereviz', 'kereviz tohumu', 'kereviz sapı', ...
        'kereviz yaprağı', 'kereviz kökü', ...
        'seleri', 'celery', ...
        'eser miktarda kereviz', 'kereviz içerebilir'
    };
    
    %% 12. ÇİKOLATA VE KAKAO (Ek Bilgi)
    % Kakao alerjisi nadir olsa da bazı kişilerde görülebilir.
    allergenDB.Kakao = {
        'kakao', 'kakao tozu', 'kakao yağı', ...
        'çikolata', 'sütlü çikolata', 'bitter çikolata', ...
        'beyaz çikolata', 'çikolata parçaları', ...
        'çikolatalı', 'çikolata kaplı', ...
        'eser miktarda çikolata', 'çikolata içerebilir', ...
        'kakao kitlesi', 'cocoa', 'kakao aroması'
    };
    
    %% 13. MEYVE ALERJİLERİ
    % Bazı meyveler oral alerji sendromuna neden olabilir
    allergenDB.Meyve = {
        'çilek', 'çilekli', 'çilek aroması', ...
        'kivi', 'kivili', ...
        'muz', 'muzlu', 'muz aroması', ...
        'şeftali', 'şeftalili', ...
        'kayısı', 'kayısılı', 'kuru kayısı', ...
        'elma', 'elmalı', 'elma suyu', ...
        'armut', 'armutlu', ...
        'kiraz', 'kirazlı', 'vişne', 'vişneli', ...
        'erik', 'erikli', 'kuru erik', ...
        'portakal', 'portakallı', 'portakal suyu', ...
        'limon', 'limonlu', 'limon suyu', ...
        'mandalina', 'mandalinalı', ...
        'ananas', 'ananaslı', ...
        'mango', 'mangolu', ...
        'papaya', 'papayalı', ...
        'hurma', 'hurmalı', ...
        'incir', 'incirli', 'kuru incir', ...
        'üzüm', 'üzümlü', 'kuru üzüm', 'kişmiş', ...
        'meyve suyu', 'meyve püresi', 'meyve aroması', ...
        'meyve konsantresi', 'doğal meyve', ...
        'karışık meyve', 'eser miktarda meyve'
    };
    
    %% 14. KURUYEMİŞ VE ÇEKİRDEK DETAYLI
    % Kuruyemiş alerjileri için daha detaylı terimler
    allergenDB.KuruyemisDetay = {
        'fındık', 'fındık ezmesi', 'fındık tozu', 'fındık yağı', ...
        'fındıklı', 'fındık aroması', 'kavrulmuş fındık', ...
        'fıstık', 'fıstık ezmesi', 'fıstık tozu', 'fıstık yağı', ...
        'badem', 'bademli', 'badem aroması', ...
        'ceviz', 'cevizli', 'ceviz içi', ...
        'antep fıstığı', 'antep fıstıklı', ...
        'kaju', 'kajulu', ...
        'ay çekirdeği', 'kabak çekirdeği', 'çekirdek', ...
        'leblebi', 'çerezlik', 'çerez karışımı', ...
        'kuruyemiş karışımı', 'mixed nuts', ...
        'eser miktarda kuruyemiş', 'kuruyemiş içerebilir', ...
        'sert kabuklu meyve', 'kabuklu yemiş'
    };
    
    %% GENEL UYARI TERIMLERI
    % OCR sonuçlarında yaygın görülen uyarı cümleleri
    allergenDB.GenelUyarilar = {
        'alerjen içerir', 'alerjen içerebilir', ...
        'eser miktarda', 'eser miktarlarda', ...
        'içerebilir', 'bulunabilir', ...
        'çapraz kontaminasyon', 'çapraz bulaşma', ...
        'aynı üretim hattında', 'aynı tesiste', ...
        'aynı ortamda üretilmiştir', ...
        'alerji uyarısı', 'alerjik kişiler dikkat', ...
        'alerjisi olanlar tüketmemelidir'
    };
    
    %% 15. BAL VE ARI ÜRÜNLERİ
    % Bal alerjisi nadir ama önemli, polen alerjisi ile bağlantılı
    allergenDB.BalVeAriUrunleri = {
        'bal', 'ballı', 'arı sütü', 'arısütü', ...
        'propolis', 'polen', 'polen tozu', ...
        'bal mumu', 'arı mumu', ...
        'çiçek balı', 'kestane balı', 'çam balı', ...
        'eser miktarda bal', 'bal içerebilir', ...
        'doğal bal', 'organik bal'
    };
    
    %% 16. MAYA VE FERMANTASYON ÜRÜNLERİ
    % Maya alerjisi candida enfeksiyonlarıyla ilişkili olabilir
    allergenDB.Maya = {
        'maya', 'ekmek mayası', 'bira mayası', ...
        'besin mayası', 'nutritional yeast', ...
        'mayalı', 'mayalanmış', 'fermente', ...
        'ekşi hamur', 'sourdough', ...
        'mayalı ürün', 'eser miktarda maya', ...
        'maya kültürü', 'aktif maya'
    };
    
    %% 17. JELATİN VE HAYVANSAL ÜRETİMLER
    % Jelatin domuz veya sığır kaynaklı olabilir, dini ve alerjik nedenlerle önemli
    allergenDB.Jelatin = {
        'jelatin', 'jelatinli', ...
        'domuz jelatini', 'sığır jelatini', ...
        'hayvansal jelatin', ...
        'kolajen', 'kolajen hidrolizatı', ...
        'eser miktarda jelatin', 'jelatin içerebilir'
    };
    
    %% 18. KATKI MADDELERİ VE KORUYUCULAR
    % Bazı katkı maddeleri alerjik reaksiyonlara neden olabilir
    allergenDB.KatkiMaddeleri = {
        'msg', 'monosodyum glutamat', 'gıda katkısı', ...
        'tartrazin', 'e102', 'sarı boya', ...
        'benzoat', 'sodyum benzoat', 'e211', ...
        'nitrit', 'nitrat', 'sodyum nitrit', 'e250', ...
        'aspartam', 'tatlandırıcı', 'yapay tatlandırıcı', ...
        'renklendirici', 'boya', 'gıda boyası', ...
        'stabilizatör', 'emülgatör', ...
        'aroma verici', 'yapay aroma', ...
        'katkı maddesi', 'kimyasal katkı'
    };
    
    %% 19. BAHARAT ALERJİLERİ
    % Nadir ama bazı baharatlar alerjik reaksiyonlara neden olabilir
    allergenDB.Baharat = {
        'baharat', 'baharat karışımı', ...
        'karabiber', 'biber', 'kırmızı biber', ...
        'kimyon', 'kişniş', 'koriander', ...
        'zencefil', 'taze zencefil', 'zencefil tozu', ...
        'tarçın', 'çubuk tarçın', 'tarçın tozu', ...
        'karanfil', 'yenibahar', ...
        'vanilya', 'vanilya özü', 'vanilin', ...
        'zerdeçal', 'hint safranı', 'turmeric', ...
        'safran', 'kekik', 'nane', 'fesleğen', ...
        'biberiye', 'adaçayı', 'defne', 'defne yaprağı'
    };
    
    %% 20. NİŞASTA VE ŞEKER TÜRLERİ
    % Farklı nişasta ve şeker kaynaklarına alerjiler olabilir
    allergenDB.NiSastaVeSeker = {
        'nişasta', 'modifiye nişasta', ...
        'mısır nişastası', 'patates nişastası', ...
        'buğday nişastası', 'pirinç nişastası', ...
        'glikoz', 'glikoz şurubu', ...
        'fruktoz', 'yüksek fruktoz', ...
        'dekstroz', 'maltodekstrin', ...
        'şeker', 'şeker kamışı', 'pancar şekeri', ...
        'kristal şeker', 'toz şeker', ...
        'sorbitol', 'mannitol', 'ksilitol', ...
        'tatlandırıcı', 'şeker içerikli'
    };
    
    %% 21. MISIR VE MISIR ÜRÜNLERİ
    % Mısır alerjisi yaygın, birçok üründe gizli bulunabilir
    allergenDB.Misir = {
        'mısır', 'mısır unu', 'mısır nişastası', ...
        'mısır yağı', 'mısır şurubu', ...
        'popcorn', 'patlamış mısır', ...
        'mısır gevreği', 'cornflakes', ...
        'mısır koçanı', 'tatlı mısır', ...
        'eser miktarda mısır', 'mısır içerebilir', ...
        'mısır bazlı', 'mısır türevi'
    };
    
    %% 22. PİRİNÇ VE PİRİNÇ ÜRÜNLERİ
    % Pirinç alerjisi nadir ama özellikle Asya'da görülür
    allergenDB.Pirinc = {
        'pirinç', 'pirinç unu', 'pirinç nişastası', ...
        'pirinç lapası', 'pirinç gevreği', ...
        'pirinç şerbet', 'pirinç tozu', ...
        'eser miktarda pirinç', 'pirinç içerebilir', ...
        'pirinç bazlı', 'pirinç sütü'
    };
    
    %% 23. SIRKE VE FERMANTE ÜRÜNLER
    % Sirke ve fermante ürünlere hassasiyet olabilir
    allergenDB.SirkeVeFermante = {
        'sirke', 'elma sirkesi', 'üzüm sirkesi', ...
        'beyaz sirke', 'bira sirkesi', ...
        'turşu', 'turşulu', 'salamura', ...
        'fermente sebze', 'lahana turşusu', ...
        'kimchi', 'kombucha', ...
        'eser miktarda sirke'
    };
    
    % Veritabanı bilgisini görüntüle
    fprintf('Alerjen Veritabanı Oluşturuldu.\n');
    fprintf('Toplam Kategori Sayısı: %d\n', length(fieldnames(allergenDB)));
    
    % Her kategorideki terim sayısını göster
    categories = fieldnames(allergenDB);
    for i = 1:length(categories)
        categoryName = categories{i};
        termCount = length(allergenDB.(categoryName));
        fprintf('  - %s: %d terim\n', categoryName, termCount);
    end

end
